# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: circleci/python:3.9

    working_directory: ~/repo

    steps:
      # Step 1: Clone repo from GitHub
      - checkout
      # Step 2: Create Virtual Env
      # Step 3: Install Dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv compute
            . compute/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . compute/bin/activate
            pytest -v --cov=compute
